version: '3'
services:
  deploy:
    build: 
      context: ./webpage
      dockerfile: Dockerfile
    image: frontend-deploy
    ports:
      - 8080:80
    restart: unless-stopped

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Contactos
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
