version: '3'
services:
  frontend:
    build: 
      context: ./webpage
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 80:80
    restart: unless-stopped

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Contactos
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
